name: create-release

on:
  pull_request:
    branches: [ develop ]

jobs:
  create_darwin_binary:
    name: Create release
    # runs-on: macos-latest
    runs-on: ubuntu-latest
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     python-version: [3.7, 3.8, 3.9]
    
    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install nuitka==0.6.19


    - name: bring_module_binary
      run: |
        python gen.py $(pwd)
        mv op.cp* ./../test
      working-directory: ./test_lib/

    - name: test_output
      run: |
        python test.py
      working-directory: ./test/

    - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.event.pull_request.body }}
          tag_name: ${{ github.event.pull_request.title }}
          generate_release_notes: true
          files: test/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}